name: 🧪 Test Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/test-backend.yml'

  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/test-backend.yml'

  workflow_dispatch:
    inputs:
      reason:
        description: "Why are you manually retrying this test?"
        required: false
        default: "Rerun backend tests"

jobs:
  test:
    name: 🧪 Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: 🔁 Log Retry Reason
        run: echo "🔁 Manual retry reason: ${{ github.event.inputs.reason }}"

      - name: ⬇️ Checkout Code
        uses: actions/checkout@v4

      - name: 💾 Cache node_modules
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: 📦 Install Dependencies
        run: npm install
        working-directory: backend

      - name: ✅ Run Tests
        run: echo "backend tests here"
        working-directory: backend
