name: 🧪 Test Frontend

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/test-frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/test-frontend.yml'
  workflow_dispatch:

jobs:
  test:
    name: 🧪 Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v4

      - name: 💾 Cache node_modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: 📦 Install Dependencies
        run: npm install
        working-directory: frontend

      - name: ✅ Run Tests
        run: echo "frontend tests here"
        working-directory: frontend
